name: kedar-new-xero
recipe: laravel
config:
  php: '7.4'
  via: apache
  webroot: app/public
  database: mysql

services:
  appserver:
    type: php:7.4
    composer: true

tooling:
  artisan:
    service: appserver
  composer:
    service: appserver
